package pqt.dss.disposal.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 01 21:35:00 PKT 2016
// ---------------------------------------------------------------------
public interface DssDisposalNoteHeaderView extends ViewObject {
    void setNVC_wfDocumentId(oracle.jbo.domain.Number value);

    void disposalNoteSearchUser();
}

