package pqt.dss.disposal.model.eo;

import java.math.BigDecimal;

import java.sql.SQLException;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 06 21:07:28 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DssDisposalNoteImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        DisposalNoteIdPk,
        AgentNoFk,
        AssetDescription,
        ReferenceNo,
        Location,
        ConditionCode,
        ReasonDisposal,
        MethodOfDisposal,
        AgeOfAsset,
        DisposalDate,
        RecommendedBy,
        SoldToContNo,
        UserIdFk,
        EnterDate,
        LastUpdatedBy,
        LastUpdatedDate,
        BranchStatus,
        DssStatus,
        BranchNotifIdFk,
        DssNotifIdFk,
        DisposalNoteHdrIdFk,
        DssDisposalNoteHeader;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DISPOSALNOTEIDPK = AttributesEnum.DisposalNoteIdPk.index();
    public static final int AGENTNOFK = AttributesEnum.AgentNoFk.index();
    public static final int ASSETDESCRIPTION = AttributesEnum.AssetDescription.index();
    public static final int REFERENCENO = AttributesEnum.ReferenceNo.index();
    public static final int LOCATION = AttributesEnum.Location.index();
    public static final int CONDITIONCODE = AttributesEnum.ConditionCode.index();
    public static final int REASONDISPOSAL = AttributesEnum.ReasonDisposal.index();
    public static final int METHODOFDISPOSAL = AttributesEnum.MethodOfDisposal.index();
    public static final int AGEOFASSET = AttributesEnum.AgeOfAsset.index();
    public static final int DISPOSALDATE = AttributesEnum.DisposalDate.index();
    public static final int RECOMMENDEDBY = AttributesEnum.RecommendedBy.index();
    public static final int SOLDTOCONTNO = AttributesEnum.SoldToContNo.index();
    public static final int USERIDFK = AttributesEnum.UserIdFk.index();
    public static final int ENTERDATE = AttributesEnum.EnterDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int BRANCHSTATUS = AttributesEnum.BranchStatus.index();
    public static final int DSSSTATUS = AttributesEnum.DssStatus.index();
    public static final int BRANCHNOTIFIDFK = AttributesEnum.BranchNotifIdFk.index();
    public static final int DSSNOTIFIDFK = AttributesEnum.DssNotifIdFk.index();
    public static final int DISPOSALNOTEHDRIDFK = AttributesEnum.DisposalNoteHdrIdFk.index();
    public static final int DSSDISPOSALNOTEHEADER = AttributesEnum.DssDisposalNoteHeader.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DssDisposalNoteImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("pqt.dss.disposal.model.eo.DssDisposalNote");
    }


    /**
     * Gets the attribute value for DisposalNoteIdPk, using the alias name DisposalNoteIdPk.
     * @return the value of DisposalNoteIdPk
     */
    public Number getDisposalNoteIdPk() {
        return (Number) getAttributeInternal(DISPOSALNOTEIDPK);
    }

    /**
     * Sets <code>value</code> as the attribute value for DisposalNoteIdPk.
     * @param value value to set the DisposalNoteIdPk
     */
    public void setDisposalNoteIdPk(Number value) {
        setAttributeInternal(DISPOSALNOTEIDPK, value);
    }

    /**
     * Gets the attribute value for AgentNoFk, using the alias name AgentNoFk.
     * @return the value of AgentNoFk
     */
    public Number getAgentNoFk() {
        return (Number) getAttributeInternal(AGENTNOFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for AgentNoFk.
     * @param value value to set the AgentNoFk
     */
    public void setAgentNoFk(Number value) {
        setAttributeInternal(AGENTNOFK, value);
    }

    /**
     * Gets the attribute value for AssetDescription, using the alias name AssetDescription.
     * @return the value of AssetDescription
     */
    public String getAssetDescription() {
        return (String) getAttributeInternal(ASSETDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for AssetDescription.
     * @param value value to set the AssetDescription
     */
    public void setAssetDescription(String value) {
        setAttributeInternal(ASSETDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for ReferenceNo, using the alias name ReferenceNo.
     * @return the value of ReferenceNo
     */
    public String getReferenceNo() {
        return (String) getAttributeInternal(REFERENCENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReferenceNo.
     * @param value value to set the ReferenceNo
     */
    public void setReferenceNo(String value) {
        setAttributeInternal(REFERENCENO, value);
    }

    /**
     * Gets the attribute value for Location, using the alias name Location.
     * @return the value of Location
     */
    public String getLocation() {
        return (String) getAttributeInternal(LOCATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Location.
     * @param value value to set the Location
     */
    public void setLocation(String value) {
        setAttributeInternal(LOCATION, value);
    }

    /**
     * Gets the attribute value for ConditionCode, using the alias name ConditionCode.
     * @return the value of ConditionCode
     */
    public String getConditionCode() {
        return (String) getAttributeInternal(CONDITIONCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ConditionCode.
     * @param value value to set the ConditionCode
     */
    public void setConditionCode(String value) {
        setAttributeInternal(CONDITIONCODE, value);
    }

    /**
     * Gets the attribute value for ReasonDisposal, using the alias name ReasonDisposal.
     * @return the value of ReasonDisposal
     */
    public String getReasonDisposal() {
        return (String) getAttributeInternal(REASONDISPOSAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReasonDisposal.
     * @param value value to set the ReasonDisposal
     */
    public void setReasonDisposal(String value) {
        setAttributeInternal(REASONDISPOSAL, value);
    }

    /**
     * Gets the attribute value for MethodOfDisposal, using the alias name MethodOfDisposal.
     * @return the value of MethodOfDisposal
     */
    public String getMethodOfDisposal() {
        return (String) getAttributeInternal(METHODOFDISPOSAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for MethodOfDisposal.
     * @param value value to set the MethodOfDisposal
     */
    public void setMethodOfDisposal(String value) {
        setAttributeInternal(METHODOFDISPOSAL, value);
    }

    /**
     * Gets the attribute value for AgeOfAsset, using the alias name AgeOfAsset.
     * @return the value of AgeOfAsset
     */
    public Date getAgeOfAsset() {
        return (Date) getAttributeInternal(AGEOFASSET);
    }

    /**
     * Sets <code>value</code> as the attribute value for AgeOfAsset.
     * @param value value to set the AgeOfAsset
     */
    public void setAgeOfAsset(Date value) {
        setAttributeInternal(AGEOFASSET, value);
    }

    /**
     * Gets the attribute value for DisposalDate, using the alias name DisposalDate.
     * @return the value of DisposalDate
     */
    public Date getDisposalDate() {
        return (Date) getAttributeInternal(DISPOSALDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DisposalDate.
     * @param value value to set the DisposalDate
     */
    public void setDisposalDate(Date value) {
        setAttributeInternal(DISPOSALDATE, value);
    }

    /**
     * Gets the attribute value for RecommendedBy, using the alias name RecommendedBy.
     * @return the value of RecommendedBy
     */
    public String getRecommendedBy() {
        return (String) getAttributeInternal(RECOMMENDEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for RecommendedBy.
     * @param value value to set the RecommendedBy
     */
    public void setRecommendedBy(String value) {
        setAttributeInternal(RECOMMENDEDBY, value);
    }

    /**
     * Gets the attribute value for SoldToContNo, using the alias name SoldToContNo.
     * @return the value of SoldToContNo
     */
    public String getSoldToContNo() {
        return (String) getAttributeInternal(SOLDTOCONTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SoldToContNo.
     * @param value value to set the SoldToContNo
     */
    public void setSoldToContNo(String value) {
        setAttributeInternal(SOLDTOCONTNO, value);
    }

    /**
     * Gets the attribute value for UserIdFk, using the alias name UserIdFk.
     * @return the value of UserIdFk
     */
    public Number getUserIdFk() {
        return (Number) getAttributeInternal(USERIDFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserIdFk.
     * @param value value to set the UserIdFk
     */
    public void setUserIdFk(Number value) {
        setAttributeInternal(USERIDFK, value);
    }

    /**
     * Gets the attribute value for EnterDate, using the alias name EnterDate.
     * @return the value of EnterDate
     */
    public Date getEnterDate() {
        return (Date) getAttributeInternal(ENTERDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EnterDate.
     * @param value value to set the EnterDate
     */
    public void setEnterDate(Date value) {
        setAttributeInternal(ENTERDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for BranchStatus, using the alias name BranchStatus.
     * @return the value of BranchStatus
     */
    public String getBranchStatus() {
        return (String) getAttributeInternal(BRANCHSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for BranchStatus.
     * @param value value to set the BranchStatus
     */
    public void setBranchStatus(String value) {
        setAttributeInternal(BRANCHSTATUS, value);
    }

    /**
     * Gets the attribute value for DssStatus, using the alias name DssStatus.
     * @return the value of DssStatus
     */
    public String getDssStatus() {
        return (String) getAttributeInternal(DSSSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for DssStatus.
     * @param value value to set the DssStatus
     */
    public void setDssStatus(String value) {
        setAttributeInternal(DSSSTATUS, value);
    }

    /**
     * Gets the attribute value for BranchNotifIdFk, using the alias name BranchNotifIdFk.
     * @return the value of BranchNotifIdFk
     */
    public Number getBranchNotifIdFk() {
        return (Number) getAttributeInternal(BRANCHNOTIFIDFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for BranchNotifIdFk.
     * @param value value to set the BranchNotifIdFk
     */
    public void setBranchNotifIdFk(Number value) {
        setAttributeInternal(BRANCHNOTIFIDFK, value);
    }

    /**
     * Gets the attribute value for DssNotifIdFk, using the alias name DssNotifIdFk.
     * @return the value of DssNotifIdFk
     */
    public Number getDssNotifIdFk() {
        return (Number) getAttributeInternal(DSSNOTIFIDFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for DssNotifIdFk.
     * @param value value to set the DssNotifIdFk
     */
    public void setDssNotifIdFk(Number value) {
        setAttributeInternal(DSSNOTIFIDFK, value);
    }


    /**
     * Gets the attribute value for DisposalNoteHdrIdFk, using the alias name DisposalNoteHdrIdFk.
     * @return the value of DisposalNoteHdrIdFk
     */
    public Number getDisposalNoteHdrIdFk() {
        return (Number) getAttributeInternal(DISPOSALNOTEHDRIDFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for DisposalNoteHdrIdFk.
     * @param value value to set the DisposalNoteHdrIdFk
     */
    public void setDisposalNoteHdrIdFk(Number value) {
        setAttributeInternal(DISPOSALNOTEHDRIDFK, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public DssDisposalNoteHeaderImpl getDssDisposalNoteHeader() {
        return (DssDisposalNoteHeaderImpl) getAttributeInternal(DSSDISPOSALNOTEHEADER);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setDssDisposalNoteHeader(DssDisposalNoteHeaderImpl value) {
        setAttributeInternal(DSSDISPOSALNOTEHEADER, value);
    }


    /**
     * @param disposalNoteIdPk key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number disposalNoteIdPk) {
        return new Key(new Object[] { disposalNoteIdPk });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
     protected void create(AttributeList attributeList) {
         super.create(attributeList);
         Date currentDate = new Date();
         setEnterDate((Date) currentDate.getCurrentDate());
         setLastUpdatedDate((Date) currentDate.getCurrentDate());
         SequenceImpl seq = new SequenceImpl("DSS_DISPOSAL_NOTE_SEQ", getDBTransaction());
         setDisposalNoteIdPk(seq.getSequenceNumber());
         
//           setBranchStatus("INCOMPLETE");
//             setDssStatus("INCOMPLETE");
         
         FacesContext fctx = FacesContext.getCurrentInstance();
         ExternalContext ectx = fctx.getExternalContext();
         HttpSession userSession = (HttpSession) ectx.getSession(false);
         try {
             setUserIdFk(new Number(userSession.getAttribute("pUserId")));
             setLastUpdatedBy(new Number(userSession.getAttribute("pUserId")));
         } catch (SQLException ex) {
             setUserIdFk(new Number(0));
             setLastUpdatedBy(new Number(0));
         }
     }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Date currentDate = new Date();
        if (operation == DML_UPDATE) {
            setLastUpdatedDate((Date) currentDate.getCurrentDate());
            FacesContext fctx = FacesContext.getCurrentInstance();
            ExternalContext ectx = fctx.getExternalContext();
            HttpSession userSession = (HttpSession) ectx.getSession(false);
            try {
                setUserIdFk(new Number(userSession.getAttribute("pUserId")));
                setLastUpdatedBy(new Number(userSession.getAttribute("pUserId")));
            } catch (SQLException ex) {
                setUserIdFk(new Number(0));
                setLastUpdatedBy(new Number(0));
            }
        }
        super.doDML(operation, e);
    }
}

