package pqt.dss.disposal.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 07 14:54:51 PKT 2016
// ---------------------------------------------------------------------
public interface DisposalAM extends ApplicationModule {
    String Apply();

    String DeleteRecord();

    void DssApprove();

    void callWorkflow(oracle.jbo.domain.Number p_document_id, String ApprovalType);

    void callDisposalWorkflow(oracle.jbo.domain.Number p_document_id);
}

